# Site settings
title: "HüzünlüArtemis"
bye_message: "HüzünlüArtemis - All Rights Reversed"
baseurl: "https://hartemis.github.io/"
url: "https://hartemis.github.io"
disqus: huzunluartemis

# Header settings
nick: "huzunluartemis"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "huzunluartemis"
blog:
    server: "github.io"
    nick: "huzunluartemis"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
