# Site settings
title: "HüzünlüArtemis"
bye_message: "HüzünlüArtemis - All Rights Reversed"
# url: "https://hartemis.github.io"
baseurl: "https://hartemis.github.io/"
disqus: huzunluartemis

# Header settings
nick: "huzunluartemis"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "huzunluartemis"
blog:
    server: "github.io"
    nick: "huzunluartemis"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/


lang: tr-TR
prefer_datetime_locale: tr
timezone: Europe/Istanbul
tagline: Revese Engineering and Malware Analysis
description: >-                        # used by seo meta and the atom feed
  A place where you can find Reversing Engineering CTF challenges writeups,
  Malware Analysis reports and some low-level geeky stuff


